name: Haskell
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Haskell GHC
    container:
      image: quay.io/change-metrics/builder
      options: --user root
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: lentille

      - name: Checkout monocle repo
        uses: actions/checkout@v2
        with:
          repository: change-metrics/monocle
          submodules: recursive
          path: monocle
          ref: refs/heads/master
          # To validate a PR with a dependent PR on Monocle
          # ref: refs/pull/394/head

      - run: ln -s /root/.cabal /github/home/.cabal
      - run: cd lentille; cabal build --enable-tests exe:macroscope exe:lentille-bugzilla exe:lentille-github exe:lentille-gitlab
      - run: cd lentille; cabal test --enable-tests --test-show-details=direct lentille-adr lentille-bugzilla-test
